apiVersion: v1
kind: Service
metadata:
  name: aws-cost-exporter
  namespace: monitoring
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "9150"
    prometheus.io/scrape: "true"
  labels:
    app: aws-cost-exporter
    product: platform
spec:
  ports:
  - port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    app: aws-cost-exporter
    product: platform
